/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_HECodeInterface */

#ifndef _Included_jni_HECodeInterface
#define _Included_jni_HECodeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_HECodeInterface
 * Method:    calculate
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_HECodeInterface_calculate
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
