/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class homomorphic_HELib_Interface */

#ifndef _Included_homomorphic_HELib_Interface
#define _Included_homomorphic_HELib_Interface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     homomorphic_HELib_Interface
 * Method:    decryptCtxt
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_homomorphic_HELib_1Interface_decryptCtxt
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     homomorphic_HELib_Interface
 * Method:    encryptPlain
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_homomorphic_HELib_1Interface_encryptPlain
  (JNIEnv *, jobject, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
